### ISSUE TITLE
Lines are in reverse order when a paragraph is rendered in a block with multiple lines after using bidi 

### ISSUE THREAD

**Issue by HadySoliman** [MeirKriheli/python-bidi#13]
whenever I try printing a paragraph or more than 10 words, lines get reversed in arabic. 

will provide more details once I get a reply. im not sure if this still active or not. 

Thank you.

**Comment by romanHerolo** [comment]
Have you ever solved this issue?

**Comment by BouhamedMohammedMounir** [comment]
We are still having the same issue.

**Comment by MeirKriheli** [comment]
Note that bidi layout algorithms have no knowledge of display types, widths, etc.

It's up to the program doing to the layout to break lines matching the width, prior to get the disaply layout.

**Comment by MeirKriheli** [comment]
No response for several weeks, closing.
