### ISSUE TITLE
Version 0.3.4 from pypi doesn't run with python 3.4

### ISSUE THREAD

**Issue by bluecube** [MeirKriheli/python-bidi#2]
Hi, sorry to bother you with this, but it would be nice if you could update the version of this library on pypi for python 3 support.

Now when I try to run the example from Readme file, I get complaints about not existing module mirror (clearly missing "." before the name). When I use version from Git, everything works fine.

Thanks

**Comment by MeirKriheli** [comment]
@bluecube Released v0.4.0.

Please let me know if you have any problems.

**Comment by bluecube** [comment]
Works perfectly, thank you.
