### ISSUE TITLE
Document packages bundled inside wheels

### ISSUE THREAD

**Issue by stefan6419846** [MeirKriheli/python-bidi#21]
The binary wheels on PyPI currently ship with a shared object compiled using Rust which seems to have some external dependencies: https://github.com/MeirKriheli/python-bidi/blob/master/Cargo.lock

For now, the corresponding packages including their version and licenses are not documented inside the *python-bidi* package itself, thus requiring additional documentation/modification work to ensure license compliance. As far as I have seen, in the source distributions at least the lock file is provided.

It would be great to have the *python-bidi* packages/wheels to provide these information for the official builds.

**Comment by MeirKriheli** [comment]
Feels out of place for a README, where exactly would you like those to be added?

**Comment by stefan6419846** [comment]
They usually are part of the main license file or of a dedicated third-party license file.

**Comment by MeirKriheli** [comment]
When I compile license compliance lists, I usually go to the source of the root package and other packages in the dep tree to make sure I get them correct.

Packages including such files may go out of sync (e.g. upon inner tree package upgrades), and missing some package in that list might be an issue.

Anyway added `LICENSE-THIRD-PARTY.yml` which should appear in the built wheels upon next release.
