### ISSUE TITLE
pip install failed after 2024.07.21(releasing v0.5.0)

### ISSUE THREAD

**Issue by wkmcyz** [MeirKriheli/python-bidi#22]
My project uses easyocr==1.7.1 , and after the release of python-bidi 0.5.0, `pip install` prints error like below.

```
Collecting python-bidi
  Using cached python_bidi-0.5.0.tar.gz (31 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Now I force the python-bidi version to 0.4.2, and it just works.

**Comment by cclauss** [comment]
What operating system are you using?
> Cargo, the Rust package manager, is not installed or is not on PATH.
> This package requires Rust and Cargo to compile extensions. Install it through
> the system's package manager or via https://rustup.rs/

**Comment by MeirKriheli** [comment]
There are pre-built wheels for many Architecture/OS/Python combos, to prevent the need for building them, see:
https://pypi.org/project/python-bidi/#files

What's your combo?

**Comment by MeirKriheli** [comment]
Could be something with the maturin generated `CI.yml`. Need to dig into it,

**Comment by MeirKriheli** [comment]
`0.5.2` explicitly states python versions for MacOS in CI.yaml. This should resolve this.

Re-open if not.
