### ISSUE TITLE
0.4.x -> 0.5 regression in reordering behavior of combining marks/mirrored glyphs

### ISSUE THREAD

**Issue by mittagessen** [MeirKriheli/python-bidi#25]
The old python implementation ran rules [L3/L4](https://www.unicode.org/reports/tr9/#L3) on the reordered output to correctly mirror glyphs and change the position of combining marks around their base character. The `unicode_bidi` rust module you're wrapping for 0.5 only implements rules L1/L2 causing the output between 0.4 and 0.5 to differ.

`unicode_bidi` also adds spurious directional markers in the output.

An example for L4:

```
# 0.4.2
>>> from bidi.algorithm import get_display
>>> get_display('א)א')
'א)א'

# 0.5.2
>>> from bidi import get_display
>>> get_display('א)א')
'\u200eא)\u200eא'
```

**Comment by MeirKriheli** [comment]
I don't see the additional markers here:
```python
>>> from bidi import get_display
>>> get_display('א)א')
'א)א'
>>> repr(get_display('א)א'))
"'א)א'"
>>> x = get_display('א)א')
>>> x[0]
'א'
>>> x[1]
')'

```
I'll provide both versions for now. Under `bidi.algorithm` the old code will reside, with older Python versions, while under the `bidi` namespace itself the new, Rust wrapping, one.

**Comment by mittagessen** [comment]
Hm, no idea what I did there but I can't reproduce the RLM markers in the output anymore.

For the mirroring your terminal probably does the it internally. Looking at the code points directly you should see something like this:

```
# 0.5.2
>>> from bidi import get_display
>>> import unicodedata
>>> unicodedata.name(get_display('א)א')[1])
'RIGHT PARENTHESIS'

# 0.4.2
>>> from bidi.algorithm import get_display
>>> import unicodedata
>>> unicodedata.name(get_display('א)א')[1])
'LEFT PARENTHESIS'
```

**Comment by MeirKriheli** [comment]
I know, that's why I did not mention the mirroring issue, just the markers ;-)

**Comment by MeirKriheli** [comment]
0.6.0 now supports both implementations:

```python
>>> from bidi import get_display
>>> x = get_display('א)א')
>>> x[1]
')'
>>> from bidi.algorithm import get_display
>>> x = get_display('א)א')
>>> x[1]
'('
```
