### ISSUE TITLE
Using python-bidi with IRC colour codes

### ISSUE THREAD

**Issue by yuvallanger** [MeirKriheli/python-bidi#3]
I am trying to use your library to replace the older pyfribidi library in the weechat script found in https://github.com/yuvallanger/weechat-biditext/ which is a fork of https://github.com/spacepluk/weechat-biditext/

When I use `bidi.algorithm.get_display(line)` on a line of weechat's buffer, IRC colour codes are stripped out. Is it possible to keep them?

python-bidi==0.4.0 and python 2.7.6

**Comment by MeirKriheli** [comment]
@yuvallanger Please provide some sample input which contains those codes, so I can try to debug it.

Thanks

**Comment by yuvallanger** [comment]
>>> "regular text\n{red}red text{regular}\n{green}green text{regular}\n{blue}blue
        text{regular}\nregular text again".format(regular=weechat.color('chat'),
        red=weechat.color('red'), green=weechat.color('green'), blue=weechat.color('blue'))
        'regular text\n\x19F03red text\x1901\n\x19F05green text\x1901\n\x19F09blue
        text\x1901\nregular text again'

**Comment by MeirKriheli** [comment]
Hmm, those chars are `BN` Looks like it's removed in [X9 stage](http://unicode.org/reports/tr9/#X9) of the algorithm:

> Remove all RLE, LRE, RLO, LRO, PDF, and BN characters.

It says that removal is optional, and one can [implement without it](http://unicode.org/reports/tr9/#Implementation_Notes). It looks more complicated, don't know when I can get around to implementing it.
