### ISSUE TITLE
Lines Reversed

### ISSUE THREAD

**Issue by antonays** [MeirKriheli/python-bidi#6]
Hi,
It appears that when using get_dislplay(str) on Hebrew strings, the output comes out in the correct direction for Hebrew words, but the lines are reversed, i.e - first line (logic) appears as last line (visual).

Example:
expected output:
לווייתן מצוי (לעתים רורקל או רורקל ענק); שם מדעי:  הוא יונק ימי ממשפחת לווייתני ענק שבסדרת הלווייתנאים. זהו הלווייתן השני בגודלו, ובעל החיים השני בגודלו החי כיום אחרי הלווייתן הכחול. הלווייתן המצוי עשוי להגיע לאורך של כמעט 27 מטר ומשקל של 120 טון אך אורכו נע בדרך כלל בין 18 ל-21 מטר ומשקלו הממוצע הוא כ-70 טון.

received output:
לאורך של כמעט 27 מטר ומשקל של 120 טון אך אורכו נע בדרך כלל בין 18 ל-21 מטר ומשקלו הממוצע הוא כ-70 טון.
הלווייתנאים. זהו הלווייתן השני בגודלו, ובעל החיים השני בגודלו החי כיום אחרי הלווייתן הכחול. הלווייתן המצוי 
לווייתן מצוי (לעתים רורקל או רורקל ענק); שם מדעי:  הוא יונק ימי ממשפחת לווייתני ענק שבסדרת

**Comment by HadySoliman** [comment]
I wonder if you ever solved this

**Comment by MeirKriheli** [comment]
Please test with 0.5.0 an re-open if needed.

PS, if the sentence is a single line (without paragraph breaks), it's up to the displaying mechanism to handle overflows correctly.
