### ISSUE TITLE
Emoji. using Python-Bidi with emoji gives me an error. 

### ISSUE THREAD

**Issue by camara90100** [MeirKriheli/python-bidi#7]
Here's the error:

`"/usr/local/lib/python2.7/dist-packages/bidi/algorithm.py", line 648, in get_display↵    resolve_implicit_levels(storage, debug)↵↵  File "/usr/local/lib/python2.7/dist-packages/bidi/algorithm.py", line 466, in resolve_implicit_levels↵    '%s not allowed here' % _ch['type']↵↵AssertionError:  not allowed here↵"`

**Comment by cclauss** [comment]
> python2.7

I think that this issue can be closed.

**Comment by MeirKriheli** [comment]
Yeah, irrelevant for Python 3. Just checked with 0.5.0:
```python
In [1]: from bidi import get_display

In [2]: msg = "שלום 😀 עולם"

In [3]: get_display(msg)
Out[3]: 'םלוע 😀 םולש'
```

Browser will change the order naturally, but no error.
